services:
  # Web Service (Node.js Dynamic Runtime with Real-Time SSE Message Hub)
  - type: web
    name: abhishek-portfolio-uir4
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
